theme = "congo"
baseURL = "https://krisetya.com/"
languageCode = "en-GB"
defaultContentLanguage = "en"
copyright = "Beltsazar Krisetya"
enableRobotsTXT = true
summaryLength = 30

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[security]
  [security.http]
    urls = ['https://sarkas\.tech/.*']
    methods = ['(?i)GET']
