theme = "congo"
baseURL = "https://krisetya.com/"
languageCode = "en-GB"
defaultContentLanguage = "en"
copyright = "Beltsazar Krisetya"
enableRobotsTXT = true
paginate = 10
summaryLength = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
